#!/usr/bin/env sh

docker rm -f manjaro-xrdp-gnome
docker build -t yunielrc/manjaro-xrdp-gnome:latest . &&
  docker run --name manjaro-xrdp-gnome \
    --privileged \
    --tty \
    --interactive \
    --shm-size 2G \
    --publish 23389:3389 \
    --publish 8022:22 \
    yunielrc/manjaro-xrdp-gnome:latest
